### ISSUE TITLE
Create a parser for the custom binder_datatype syntax

### ISSUE THREAD

**Issue by jvanbruegge** [jvanbruegge/binder_datatypes#7]
Currently, datatypes have to be created from ML. Similar to normal datatypes, binder_datatypes should have custom syntax to define datatypes easily. The idea at the moment is to support syntax like this:
```isabelle
binder_datatype (FVars: 'a, 'b) foo =
  Var 'a
| Ann 'b
| Lam x::'a t::"('a, 'b) foo" binds x in t
| App "('a, 'b) foo" "('a, 'b) foo"
| LetRec "(xs::'a * ts::(('a, 'b) foo)) list" t::"('a, 'b) foo" binds xs in ts t
for
  map: vvsubst
```
Open questions about syntax:
- [ ] It would be convenient for the user to work with a concrete variable type. Should we automate this and how should we specify this? Current idea: separate command
- [ ] Should we automate singular substitution and multi- (list) substitution? Would be more convenient for the user as this could discharge all cardinality assumptions.

Prerequisites:
- [ ] #9

**Comment by dtraytel** [comment]
I think instantiating variables with concrete types could be the task for a separate command. Moreover, I'm not sure what you mean by "could discharge all cardinality assumptions": e.g., substitutions still have to be small support.

**Comment by jvanbruegge** [comment]
Oh yes, I mixed that up with singlar/list substitution
